---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-edit-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deploy_edit
subjects:
- kind: User
  name: deploy_edit
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: deploy-edit-role
  apiGroup: rbac.authorization.k8s.io