apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx1
  name: nginx1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
    spec:
      containers:
      - image: nginx:latest
        name: nginx1
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-nginx
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      volumes:
        - name: config-nginx
          configMap:
            name: nginx1-configmap
---

apiVersion: v1
data:
  default.conf: |-
    server {
        listen 80 default_server;
        server_name _;
        default_type text/plain;

        location / {
            return 200 'nginx1\n';
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx1-configmap
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx1
  name: nginx1-np
spec:
  type: NodePort
  selector:
    app: nginx1
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
